"""Public API for reusable built-in agent tools."""

from .builtin import (
    BashResult,
    BuiltinToolExecutor,
    GrepMatch,
    ToolError,
    ToolPermissionError,
    ToolPermissionPolicy,
    ToolSandboxPolicy,
)
from .shell_parser import (
    ShellParseError,
    ShellSubsetParser,
    ShlexTokenizer,
    parse_shell_command,
)
from .shell_registry import (
    ShellCommandContext,
    ShellCommandHandler,
    ShellCommandRegistry,
    ShellCommandResult,
    ShellRegistryError,
)
from .shell_runtime import (
    ShellCancellationToken,
    ShellEventSink,
    ShellExecutionCancelledError,
    ShellExecutionError,
    ShellExecutionEvent,
    ShellExecutionEventKind,
    emit_shell_event,
)
from .shell_subset import (
    PipelineCondition,
    ShellEnvAssignment,
    ShellLimits,
    ShellPipeline,
    ShellPipelineStep,
    ShellProgram,
    ShellRedirection,
    ShellSimpleCommand,
    ShellSubsetError,
    ShellSubsetFeatures,
    validate_shell_program,
)

__all__ = [
    "BashResult",
    "BuiltinToolExecutor",
    "GrepMatch",
    "PipelineCondition",
    "ShellCancellationToken",
    "ShellCommandContext",
    "ShellCommandHandler",
    "ShellCommandRegistry",
    "ShellCommandResult",
    "ShellEnvAssignment",
    "ShellEventSink",
    "ShellExecutionCancelledError",
    "ShellExecutionError",
    "ShellExecutionEvent",
    "ShellExecutionEventKind",
    "ShellLimits",
    "ShellParseError",
    "ShellPipeline",
    "ShellPipelineStep",
    "ShellProgram",
    "ShellRedirection",
    "ShellRegistryError",
    "ShellSimpleCommand",
    "ShellSubsetError",
    "ShellSubsetFeatures",
    "ShellSubsetParser",
    "ShlexTokenizer",
    "ToolError",
    "ToolPermissionError",
    "ToolPermissionPolicy",
    "ToolSandboxPolicy",
    "emit_shell_event",
    "parse_shell_command",
    "validate_shell_program",
]
